version: 2

models:
  - name: stg_local_bike_ds_t_brand
    description: "This model contains information about brand of products"
    columns:
      - name: brand_id
        description: "Primary key, unique identifier for each brand."
        tests:
            - unique
            - not_null

  - name: stg_local_bike_ds_t_categories
    description: "This model contains information about categories of products."
    columns:
      - name: category_id
        description: "Primary key, unique identifier for each category."
        tests:
            - unique
            - not_null

  - name: stg_local_bike_ds_t_customers
    description: "This model contains information about customers."
    columns:
      - name: customer_id
        description: "Primary key, unique identifier for each customers."
        tests:
            - unique
            - not_null

  - name: stg_local_bike_ds_t_order_items
    description: "This model contains information about each item included in an order."
    columns:
      - name: oitem_id
        description: "Primary key, unique identifier for each order_item it's a combination of order_id item_id and product_id."
        tests:
            - unique
            - not_null
      - name: order_id
        description: "FK to stg_local_bike_ds_t_orders"
        tests:
            - not_null
            - relationships:
                name: order_id_foreign_key_in_stg_local_bike_ds_t_orders
                to: ref('stg_local_bike_ds_t_orders')
                field: order_id
      - name: product_id
        description: "FK to stg_local_bike_ds_t_products"
        tests:
            - not_null
            - relationships:
                name: item_id_foreign_key_in_stg_local_bike_ds_t_products
                to: ref('stg_local_bike_ds_t_products')
                field: product_id

  - name: stg_local_bike_ds_t_orders
    description: "This model contains information about orders."
    columns:
      - name: order_id
        description: "Primary key, unique identifier for each order."
        tests:
            - unique
            - not_null
      - name: customer_id
        description: "FK to stg_local_bike_ds_t_customer"
        tests:
            - not_null
            - relationships:
                name: customer_id_foreign_key_in_stg_local_bike_ds_t_customers
                to: ref('stg_local_bike_ds_t_customers')
                field: customer_id
      - name: store_id
        description: "FK to stg_local_bike_ds_t_stores"
        tests:
            - not_null
            - relationships:
                name: store_id_foreign_key_in_stg_local_bike_ds_t_stores
                to: ref('stg_local_bike_ds_t_stores')
                field: store_id        
      - name: staff_id
        description: "FK to stg_local_bike_ds_t_staffs"
        tests:
            - not_null
            - relationships:
                name: staff_id_foreign_key_in_stg_local_bike_ds_t_staffs
                to: ref('stg_local_bike_ds_t_staffs')
                field: staff_id

  - name: stg_local_bike_ds_t_products
    description: "This model contains details of products available for sale, contain product brand / category / model year / price."
    columns:
      - name: product_id
        description: "Primary key, unique identifier for each product."
        tests:
            - unique
            - not_null
      - name: brand_id
        description: "FK to stg_local_bike_ds_t_brand"
        tests:
            - not_null
            - relationships:
                name: brand_id_foreign_key_in_stg_local_bike_ds_t_brand
                to: ref('stg_local_bike_ds_t_brand')
                field: brand_id
      - name: category_id
        description: "FK to stg_local_bike_ds_t_categories"
        tests:
            - not_null
            - relationships:
                name: category_id_foreign_key_in_stg_local_bike_ds_t_categories
                to: ref('stg_local_bike_ds_t_categories')
                field: category_id

  - name: stg_local_bike_ds_t_staffs
    description: "This model contains information about the sellers and staff."
    columns:
      - name: staff_id
        description: "Primary key, unique identifier for each staff member."
        tests:
            - unique
            - not_null
      - name: store_id
        description: "FK to stg_local_bike_ds_t_stores"
        tests:
            - not_null
            - relationships:
                name: store_id_foreign_key_in_stg_local_bike_ds_t_stores
                to: ref('stg_local_bike_ds_t_stores')
                field: store_id
      - name: manager_id
        description: "self reference to stg_local_bike_ds_t_staffs"

  - name: stg_local_bike_ds_t_stocks
    description: "This model contains stocks-related information."
    columns:
      - name: store_id
        description: "FK to stg_local_bike_ds_t_stores."
        tests:
            - not_null
            - relationships:
                name: store_id_foreign_key_in_stg_local_bike_ds_t_stores
                to: ref('stg_local_bike_ds_t_stores')
                field: store_id
      - name: product_id
        description: "FK to stg_local_bike_ds_t_products"
        tests:
            - not_null
            - relationships:
                name: product_id_foreign_key_in_stg_local_bike_ds_t_products
                to: ref('stg_local_bike_ds_t_products')
                field: product_id

  - name: stg_local_bike_ds_t_stores
    description: "This model contains store-related information. store name / phone / email / address"
    columns:
      - name: store_id
        description: "FK to stg_local_bike_ds_t_stores."
        tests:
            - unique
            - not_null