models:
  - name: mrt_local_bike_ds_customer_orders
    description: '{{ doc("mrt_local_bike_ds_customer_orders") }}'
    columns:
      - name: customer_id
        description: "Primary key, unique identifier for each customer."
        tests:
            - unique
            - not_null

  - name: mrt_local_bike_ds_order_monthly_report
    description: '{{ doc("mrt_local_bike_ds_order_monthly_report") }}'
    columns:
      - name: order_id
        description: "Primary key, unique identifier for each order."
        tests:
            - unique
            - not_null

  - name: mrt_local_bike_ds_product_stores
    description: '{{ doc("mrt_local_bike_ds_product_stores") }}'
    columns:
      - name: product_id
        description: "Primary key, unique identifier for each product."
        tests:
            - unique
            - not_null


  - name: mrt_local_bike_ds_stores_orders
    description: '{{ doc("mrt_local_bike_ds_stores_orders") }}'
    columns:
      - name: store_id
        description: "Primary key, unique identifier for each store."
        tests:
            - unique
            - not_null



